server:
  port: 8080

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:inditex
    driver-class-name: org.h2.Driver
    username: app
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update