server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:inditex
    driver-class-name: org.h2.Driver
    username: app
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true